### ISSUE TITLE
Create GitHub actions to test any code before merging

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Truth-Loop#160]
### Background on the problem the feature will solve/improved user experience
Add GitHub Actions to test and build new code pushed to a branch or committed to a pull request. Code that passes all the steps in the GitHub action can be merged in the repository.

### Describe the solution you'd like
A GitHub action runs whenever code is committed to any branch or PR is made to the main branch for each of the following components:
- [ ] server
- [ ] client
- [ ] react/client

Refer to a similar action that was implemented for the[ UI folder in Five Fifths Voter project.](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/issues/232)

Each action will 
- [ ] install dependencies 
- [ ] build for production 
- [ ] run all tests
- [ ] linting with [prettier](https://prettier.io/docs/en/index.html). Discuss with the team on what linter to use.

### Tasks
- [ ] Ensure install, build and lint steps run locally on your system
- [ ] Read more about [GitHub actions](https://docs.github.com/en/actions/learn-github-actions) 
- [ ] Create an action for each folder. You can read more [JavaScript build actions here](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python).
- [ ] Commit and push your GitHub action code.
- [ ] Go to the [Actions tab](https://github.com/Call-for-Code-for-Racial-Justice/FairChange/actions) to see if it worked.

### Acceptance Criteria 
GitHub action runs for every new code commit and PR.

FYI @demilolu @davidnixon

**Comment by arianahl** [comment]
I've done the same for FairChange. Can I take this issue?

**Comment by arianahl** [comment]
Hi! I added github actions for the server and client. The server one is giving me a lot of errors when executing npm test. 
Does anyone knows if the tests are broken or if I am missing a setup step?
