### ISSUE TITLE
Create Epics and prioritize User stories 

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Truth-Loop#257]
### Describe the solution you'd like
User stories

- [ ] As a user, I need to search for policies by postcode so I can discover relevant legislation (Filtered Search/Landing)
- [ ] As a user, I need to browse general policies so I can discover/explore them without needing prior knowledge (Filtered Search/Search)
- [ ] As a user, I need to access my testimonials so I can see my activity (Record and view/ TBD)
- [ ] As a user, I need to search for policies by state and category so I can discover policies I'm interested in (Filtered Search/Search)
- [ ] As a user, I need to explore policies by category so I can learn about policies I'm interested in 
- [ ] As a user, I need to see both policies and testimonials in my search reuslt that are relevant to my filtered search so I have the choice of how to learn about policies
- [ ] As a user, I need to record video clips so I can share my story in them 
- [ ] As a user, I need to provide my name and email address when posting a video so I can be identfied and verified
- [ ] As a user, I need to provide my privacy preferences when posting a video so I can feel confident that my data is protected
- [ ] As a user, I need the policy I'm recording a video testimonial about to be tagged/attached to my video so I and other users can identify the topic of my testimonial
- [ ] As a user, I need to watch video testimonials so I can learn about policy impact
- [ ] As a user, I need to be able to watch videos consecutively to simplify my learning expereience
- [ ] As a user, I need to be able to skip videos so I don't have to spend time watching content I'm not interested in 
- [ ] As a user, I need the policy a testimonial video is about to be visible and tagged to the video so I can identify and navigate the content on the app 
- [ ] As a user, I need advocacy groups that are relevenat to a testimonial or policy I'm viewing to be linked so I can find out how to get involved
- [ ] As a user, I need to see policies that are related so I can learn more about a topic
- [ ] As a user, I need to access policy information and metadata e.g. policy summaries, sponsors, date introduced etc so that I can educate myself on the policy
- [ ] As a user, I need to view an example/template of a video testimonial so I have guidance on how to communicate my story well
- [ ] As a user, I need to view text instructions on what to touch on in video testimonial so I can communicate my story well

### Tasks 
Description of the development tasks needed to complete this issue, including tests, 

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.

**Comment by sharonosahon** [comment]
Updated user stories:

- [ ] As a user, I need to search for policies by location/area so I can discover relevant legislation (Filtered Search/Landing)
- [ ]  As a user, I need to browse general policies so I can discover/explore them without needing prior knowledge (Filtered Search/Search)
- [ ]  As a user, I need to access my testimonials so I can see my activity (Record and view/ TBD)
- [ ]  As a user, I need to search for policies by location/area and category so I can discover policies I'm interested in (Filtered Search/Search)
- [ ]  As a user, I need to explore policies by category so I can learn about policies I'm interested in
- [ ]  As a user, I need to see both policies and testimonials in my search result that are relevant to my filtered search so I have the choice of how to learn about policies
- [ ]  As a user, I need to record video clips so I can share my story in them
- [ ]  As a user, I need to provide my name and email address when posting a video so I can be identified and verified
- [ ]  As a user, I need to provide my privacy preferences when posting a video so I can feel confident that my data is protected
- [ ]  As a user, I need the policy I'm recording a video testimonial about to be tagged/attached to my video so I and other users can identify the topic of my testimonial
- [ ]  As a user, I need to watch video testimonials so I can learn about policy impact
- [ ]  As a user, I need to be able to watch videos consecutively to simplify my learning experience
- [ ]  As a user, I need to be able to skip videos so I don't have to spend time watching content I'm not interested in
- [ ]  As a user, I need the policy a testimonial video is about to be visible and tagged to the video so I can identify and navigate the content on the app
- [ ]  As a user, I need advocacy groups that are relevant to a testimonial or policy I'm viewing to be linked so I can find out how to get involved
- [ ]  As a user, I need to see policies that are related so I can learn more about a topic
- [ ]  As a user, I need to access policy information and metadata e.g. policy summaries, sponsors, date introduced etc so that I can educate myself on the policy
- [ ]  As a user, I need to view an example/template of a video testimonial so I have guidance on how to communicate my story well
- [ ]  As a user, I need to view text instructions on what to touch on in video testimonial so I can communicate my story well
