### ISSUE TITLE
Epic: Filtered search for policies and testimonials

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Truth-Loop#258]
### User Stories

- [ ]  As a user, I need to search for policies by postcode so I can discover relevant legislation (Filtered Search/Landing)
- [ ] As a user, I need to browse general policies so I can discover/explore them without needing prior knowledge (Filtered Search/Search)
- [ ] As a user, I need to search for policies by state and category so I can discover policies I'm interested in (Filtered Search/Search)
- [ ] As a user, I need to explore policies by category so I can learn about policies I'm interested in
- [ ] As a user, I need to see both policies and testimonials in my search reuslt that are relevant to my filtered search so I have the choice of how to learn about policies

### Tasks 
Description of the development tasks needed to complete this issue, including tests, 

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.

**Comment by ed-snodgrass** [comment]
Here is one related issue:

https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/issues/175
