### ISSUE TITLE
Epic: Record and view video testimonials

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Truth-Loop#259]
### User Stories

- [ ] As a user, I need to access my testimonials so I can see my activity
- [ ] As a user, I need to record video clips so I can share my story in them
- [ ] As a user, I need to access my testimonials so I can see my activity
- [ ] As a user, I need to provide my name and email address when posting a video so I can be identfied and verified
- [ ] As a user, I need to provide my privacy preferences when posting a video so I can feel confident that my data is protected
- [ ] As a user, I need the policy I'm recording a video testimonial about to be tagged/attached to my video so I and other users can identify the topic of my testimonial
- [ ] As a user, I need to watch video testimonials so I can learn about policy impact
- [ ] As a user, I need to be able to watch videos consecutively to simplify my learning experience
- [ ] As a user, I need to be able to skip videos so I don't have to spend time watching content I'm not interested in
- [ ] As a user, I need the policy a testimonial video is about to be visible and tagged to the video so I can identify and navigate the content on the app
- [ ] As a user, I need to view an example/template of a video testimonial so I have guidance on how to communicate my story well
- [ ] As a user, I need to view text instructions on what to touch on in video testimonial so I can communicate my story well

### Tasks 
Description of the development tasks needed to complete this issue, including tests, 

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.
